/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as KitInstaladoresRouteImport } from './routes/kit-instaladores'
import { Route as RenovacionesRouteImport } from './routes/renovaciones'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as UsuarioFinalRouteImport } from './routes/usuario-final'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const KitInstaladoresRoute = KitInstaladoresRouteImport.update({
  id: '/kit-instaladores',
  path: '/kit-instaladores',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacionesRoute = RenovacionesRouteImport.update({
  id: '/renovaciones',
  path: '/renovaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuarioFinalRoute = UsuarioFinalRouteImport.update({
  id: '/usuario-final',
  path: '/usuario-final',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/kit-instaladores': typeof KitInstaladoresRoute
  '/renovaciones': typeof RenovacionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/usuario-final': typeof UsuarioFinalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/kit-instaladores': typeof KitInstaladoresRoute
  '/renovaciones': typeof RenovacionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/usuario-final': typeof UsuarioFinalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/kit-instaladores': typeof KitInstaladoresRoute
  '/renovaciones': typeof RenovacionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/usuario-final': typeof UsuarioFinalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/kit-instaladores'
    | '/renovaciones'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/usuario-final'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/kit-instaladores'
    | '/renovaciones'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/usuario-final'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/kit-instaladores'
    | '/renovaciones'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/usuario-final'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  KitInstaladoresRoute: typeof KitInstaladoresRoute
  RenovacionesRoute: typeof RenovacionesRoute
  ServiciosRoute: typeof ServiciosRoute
  TerminosRoute: typeof TerminosRoute
  TiendaRoute: typeof TiendaRoute
  UsuarioFinalRoute: typeof UsuarioFinalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit-instaladores': {
      id: '/kit-instaladores'
      path: '/kit-instaladores'
      fullPath: '/kit-instaladores'
      preLoaderRoute: typeof KitInstaladoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovaciones': {
      id: '/renovaciones'
      path: '/renovaciones'
      fullPath: '/renovaciones'
      preLoaderRoute: typeof RenovacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuario-final': {
      id: '/usuario-final'
      path: '/usuario-final'
      fullPath: '/usuario-final'
      preLoaderRoute: typeof UsuarioFinalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  KitInstaladoresRoute: KitInstaladoresRoute,
  RenovacionesRoute: RenovacionesRoute,
  ServiciosRoute: ServiciosRoute,
  TerminosRoute: TerminosRoute,
  TiendaRoute: TiendaRoute,
  UsuarioFinalRoute: UsuarioFinalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
