/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as PanelTokenRouteImport } from './routes/panel.$token'
import { Route as ApiPublicCronResumenPendientesRouteImport } from './routes/api/public/cron/resumen-pendientes'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTokenRoute = PanelTokenRouteImport.update({
  id: '/panel/$token',
  path: '/panel/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronResumenPendientesRoute =
  ApiPublicCronResumenPendientesRouteImport.update({
    id: '/api/public/cron/resumen-pendientes',
    path: '/api/public/cron/resumen-pendientes',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/panel/$token': typeof PanelTokenRoute
  '/api/public/cron/resumen-pendientes': typeof ApiPublicCronResumenPendientesRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/panel/$token': typeof PanelTokenRoute
  '/api/public/cron/resumen-pendientes': typeof ApiPublicCronResumenPendientesRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/panel/$token': typeof PanelTokenRoute
  '/api/public/cron/resumen-pendientes': typeof ApiPublicCronResumenPendientesRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/panel/$token'
    | '/api/public/cron/resumen-pendientes'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/panel/$token'
    | '/api/public/cron/resumen-pendientes'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/servicios'
    | '/terminos'
    | '/tienda'
    | '/panel/$token'
    | '/api/public/cron/resumen-pendientes'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ServiciosRoute: typeof ServiciosRoute
  TerminosRoute: typeof TerminosRoute
  TiendaRoute: typeof TiendaRoute
  PanelTokenRoute: typeof PanelTokenRoute
  ApiPublicCronResumenPendientesRoute: typeof ApiPublicCronResumenPendientesRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/$token': {
      id: '/panel/$token'
      path: '/panel/$token'
      fullPath: '/panel/$token'
      preLoaderRoute: typeof PanelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/resumen-pendientes': {
      id: '/api/public/cron/resumen-pendientes'
      path: '/api/public/cron/resumen-pendientes'
      fullPath: '/api/public/cron/resumen-pendientes'
      preLoaderRoute: typeof ApiPublicCronResumenPendientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ServiciosRoute: ServiciosRoute,
  TerminosRoute: TerminosRoute,
  TiendaRoute: TiendaRoute,
  PanelTokenRoute: PanelTokenRoute,
  ApiPublicCronResumenPendientesRoute: ApiPublicCronResumenPendientesRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
